### ISSUE TITLE
XML Validation of view/adminhtml/ui_component/cms_page_form.xml failed

### ISSUE THREAD

**Issue by m-schreiber** [magesuite/cms-tag-manager#1]
When in Developer-Mode, the XML-Schema-Validation for `view/adminhtml/ui_component/cms_page_form.xml` fails with
```
Exception #0 (Magento\Framework\Exception\LocalizedException): The XML in file "/var/www/vendor/creativestyle/magesuite-cms-tag-manager/view/adminhtml/ui_component/cms_page_form.xml" is invalid:
Element 'argument': This element is not expected. Expected is one of ( bookmark, boolean, button, checkbox, checkboxset, colorPicker, component, container, dataSource, dataProvider ).
Line: 21
```
Removing the following Lines fixes the Problem:
https://github.com/magesuite/cms-tag-manager/blob/0153d1100b6fdf6e4cdf29771ad4e6f41f6f922d/view/adminhtml/ui_component/cms_page_form.xml#L21 to
https://github.com/magesuite/cms-tag-manager/blob/0153d1100b6fdf6e4cdf29771ad4e6f41f6f922d/view/adminhtml/ui_component/cms_page_form.xml#L25

and

https://github.com/magesuite/cms-tag-manager/blob/0153d1100b6fdf6e4cdf29771ad4e6f41f6f922d/view/adminhtml/ui_component/cms_page_form.xml#L45 to
https://github.com/magesuite/cms-tag-manager/blob/0153d1100b6fdf6e4cdf29771ad4e6f41f6f922d/view/adminhtml/ui_component/cms_page_form.xml#L49

**Comment by berbua** [comment]
Hello @m-schreiber , please be informed that issue has been fixed with https://github.com/magesuite/cms-tag-manager/commit/53c9a13c25934b3f7ffba7b7af3aeaf13ae155c8
